<?php
//////////////////////////////////////////////////////////////
// This class generated by a tool on 2015-02-13 at 13:51:58 //
//////////////////////////////////////////////////////////////
class Dostawa { 
  public $_id = null;
  public $_adres = null;

  function save($db) {
    if(is_null($this->_id)) {

      $query = $db->prepare("INSERT INTO `dostawa` VALUES (null,?);");
      $query->execute(array($this->_adres));
      $this->_id = $db->lastInsertId();

    }
    else {
      $query = $db->prepare("UPDATE `dostawa` SET `adres`=? WHERE `id`=? LIMIT 1;");
      $query->execute(array($this->_adres,$this->_id));
    }
  }

  function delete($db) {
    if(is_null($this->_id)) {
      return;
    }
    else {
      $query = $db->prepare("DELETE FROM `dostawa` WHERE `id`=? LIMIT 1;");
      $query->execute(array($this->_id));
    }
  }

  function get($db, $id) {
    $query = $db->prepare("SELECT `id`,`adres` FROM `dostawa` WHERE `id`=? LIMIT 1;");
    $query->execute(array($id));
    foreach ($query->fetchAll() as $row_id => $row_data) {
      $this->_id = $row_data["id"];
      $this->_adres = $row_data["adres"];
    }
  }
}

?>