<?php
//////////////////////////////////////////////////////////////
// This class generated by a tool on 2015-02-13 at 13:51:58 //
//////////////////////////////////////////////////////////////
class dostawa { 
  public $_id = null;
  public $_adres = null;

  function save($db) {
    if(is_null($this->_)) {
      $query = $db->prepare("INSERT INTO `dostawa` VALUES (?,?);");
      $query->execute(array($this->_id,$this->_adres));
      $this->_id = $db->lastInsertId();
    }
    else {
      $query = $db->prepare("UPDATE `dostawa` SET `id`=?,`adres`=? WHERE ``=? LIMIT 1;");
      $query->execute(array($this->_id,$this->_adres,$this->_));
    }
  }

  function delete($db) {
    if(is_null($this->_)) {
      return;
    }
    else {
      $query = $db->prepare("DELETE FROM `dostawa` WHERE ``=? LIMIT 1;");
      $query->execute(array($this->_));
    }
  }

  function get($db, $id) {
    $query = $db->prepare("SELECT ``,`id`,`adres` FROM `dostawa` WHERE ``=? LIMIT 1;");
    $query->execute(array($id));
    foreach ($query->fetchAll() as $row_id => $row_data) {
      $this->_ = $row_data[""];
      $this->_id = $row_data["id"];
      $this->_adres = $row_data["adres"];
    }
  }
}

?>