<?php
//////////////////////////////////////////////////////////////
// This class generated by a tool on 2015-02-13 at 13:51:58 //
//////////////////////////////////////////////////////////////
class dostawa { 
  private $_id = null;
  private $_adres = null;

  function getid() {
    return (int)$this->_id;
  }
  function getadres() {
    return $this->_adres;
  }
  function setid($newvalue) {
    if(is_null($newvalue)) {
      throw new Exception("Value cannot be null - id");
    }
    if(gettype($newvalue) != "integer") {
      throw new Exception("Value not integer - ".$newvalue);
    }
    if(strlen($newvalue) > 11) {
      throw new Exception("Value size larger then then - 11 - ".$newvalue);
    }
    $this->_id = (int)$newvalue;
  }
  function setadres($newvalue) {
    if(is_null($newvalue)) {
      throw new Exception("Value cannot be null - adres");
    }
    if(gettype($newvalue) != "string") {
      throw new Exception("Value not string - ".$newvalue);
    }
    $this->_adres = $newvalue;
  }

  function save($db) {
    if(is_null($this->_)) {
      $query = $db->prepare("INSERT INTO `dostawa` VALUES (?,?);");
      $query->execute(array($this->_id,$this->_adres));
      $this->_ = $db->lastInsertId();
    }
    else {
      $query = $db->prepare("UPDATE `dostawa` SET `id`=?,`adres`=? WHERE ``=? LIMIT 1;");
      $query->execute(array($this->_id,$this->_adres,$this->_));
    }
  }

  function delete($db) {
    if(is_null($this->_)) {
      return;
    }
    else {
      $query = $db->prepare("DELETE FROM `dostawa` WHERE ``=? LIMIT 1;");
      $query->execute(array($this->_));
    }
  }

  function get($db, $id) {
    if(gettype($id) != "integer") {
      throw new Exception("Value not integer");
    }
    else {
      $query = $db->prepare("SELECT ``,`id`,`adres` FROM `dostawa` WHERE ``=? LIMIT 1;");
      $query->execute(array($id));
      foreach ($query->fetchAll() as $row_id => $row_data) {
        $this->_ = $row_data[""];
        $this->_id = $row_data["id"];
        $this->_adres = $row_data["adres"];
      }
    }
  }
}

?>