<?php

//////////////////////////////////////////////////////////////
// This class generated by a tool on 2015-02-13 at 13:51:58 //
//////////////////////////////////////////////////////////////
class film { 
  public $_id = null;
  public $_nazwa = null;
  public $_cena = null;
  public $_img_url = null;
  public $_opis = null;

  // Zapisanie obiektu do bazy
  function save($db) {
    // Jeżeli to jest nowo dodany film
    if(is_null($this->_id)) {
      $query = $db->prepare("INSERT INTO `film` VALUES (NULL,?,?,?,?);");
      $query->execute(array($this->_nazwa,$this->_cena,$this->_img_url,$this->_opis));
      $this->_id = $db->lastInsertId();
    }
    else {
      $query = $db->prepare("UPDATE `film` SET `nazwa`=?,`cena`=?,`img_url`=?,`opis`=? WHERE `id`=? LIMIT 1;");
      $query->execute(array($this->_nazwa,$this->_cena,$this->_img_url,$this->_opis,$this->_id));
    }
  }

  function delete($db) {
    $query = $db->prepare("DELETE FROM `film` WHERE `id`=? LIMIT 1;");
    $query->execute(array($this->_id));
  }

  function get($db,$id) {
    $query = $db->prepare("SELECT `id`,`nazwa`,`cena`,`img_url`,`opis` FROM `film` WHERE `id`=? LIMIT 1;");
    $query->execute(array($id));
    foreach ($query->fetchAll() as $row_id => $row_data) {
      $this->_id = $row_data["id"];
      $this->_nazwa = $row_data["nazwa"];
      $this->_cena = $row_data["cena"];
      $this->_img_url = $row_data["img_url"];
      $this->_opis = $row_data["opis"];
    }
  }
}

?>