<?php
//////////////////////////////////////////////////////////////
// This class generated by a tool on 2015-02-13 at 13:51:58 //
//////////////////////////////////////////////////////////////
class koszyk { 
  private $_id = null;
  private $_czas_zamowienia = null;
  private $_dostawa_id = null;

  function getid() {
    return $this->_id;
  }
  function getdostawa_id() {
    return (int)$this->_dostawa_id;
  }
  function setczas_zamowienia($newvalue) {
    if(is_null($newvalue)) {
      throw new Exception("Value cannot be null - czas_zamowienia");
    }
    // !!!WARNING!!! Unknown type "czas_zamowienia" may not save correctly. You can ignore this if you know how to handle the database type yourself.
    $this->_czas_zamowienia = $newvalue;
  }
  function setdostawa_id($newvalue) {
    if(is_null($newvalue)) {
      throw new Exception("Value cannot be null - dostawa_id");
    }
    if(gettype($newvalue) != "integer") {
      throw new Exception("Value not integer - ".$newvalue);
    }
    if(strlen($newvalue) > 11) {
      throw new Exception("Value size larger then then - 11 - ".$newvalue);
    }
    $this->_dostawa_id = (int)$newvalue;
  }

  function save($db) {
    if(is_null($this->_id)) {
      $query = $db->prepare("INSERT INTO `koszyk` VALUES (NULL,?,?);");
      $query->execute(array($this->_czas_zamowienia,$this->_dostawa_id));
      $this->_id = $db->lastInsertId();
    }
    else {
      $query = $db->prepare("UPDATE `koszyk` SET `czas_zamowienia`=?,`dostawa_id`=? WHERE `id`=? LIMIT 1;");
      $query->execute(array($this->_czas_zamowienia,$this->_dostawa_id,$this->_id));
    }
  }

  function delete($db) {
    if(is_null($this->_id)) {
      return;
    }
    else {
      $query = $db->prepare("DELETE FROM `koszyk` WHERE `id`=? LIMIT 1;");
      $query->execute(array($this->_id));
    }
  }

  function get($db,$id) {
    if(gettype($id) != "integer") {
      throw new Exception("Value not integer");
    }
    else {
      $query = $db->prepare("SELECT `id`,`czas_zamowienia`,`dostawa_id` FROM `koszyk` WHERE `id`=? LIMIT 1;");
      $query->execute(array($id));
      foreach ($query->fetchAll() as $row_id => $row_data) {
        $this->_id = $row_data["id"];
        $this->_czas_zamowienia = $row_data["czas_zamowienia"];
        $this->_dostawa_id = $row_data["dostawa_id"];
      }
    }
  }
}

//////////////////////////////////////////////////////////////
// This class generated by a tool on 2015-02-13 at 13:51:58 //
//////////////////////////////////////////////////////////////
class koszyk_film { 
  private $_film_id = null;
  private $_koszyk_id = null;

  function getfilm_id() {
    return (int)$this->_film_id;
  }
  function getkoszyk_id() {
    return (int)$this->_koszyk_id;
  }
  function setfilm_id($newvalue) {
    if(is_null($newvalue)) {
      throw new Exception("Value cannot be null - film_id");
    }
    if(gettype($newvalue) != "integer") {
      throw new Exception("Value not integer - ".$newvalue);
    }
    if(strlen($newvalue) > 11) {
      throw new Exception("Value size larger then then - 11 - ".$newvalue);
    }
    $this->_film_id = (int)$newvalue;
  }
  function setkoszyk_id($newvalue) {
    if(is_null($newvalue)) {
      throw new Exception("Value cannot be null - koszyk_id");
    }
    if(gettype($newvalue) != "integer") {
      throw new Exception("Value not integer - ".$newvalue);
    }
    if(strlen($newvalue) > 11) {
      throw new Exception("Value size larger then then - 11 - ".$newvalue);
    }
    $this->_koszyk_id = (int)$newvalue;
  }

  function save($db) {
    if(is_null($this->_)) {
      $query = $db->prepare("INSERT INTO `koszyk_film` VALUES (?,?);");
      $query->execute(array($this->_film_id,$this->_koszyk_id));
      $this->_ = $db->lastInsertId();
    }
    else {
      $query = $db->prepare("UPDATE `koszyk_film` SET `film_id`=?,`koszyk_id`=? WHERE ``=? LIMIT 1;");
      $query->execute(array($this->_film_id,$this->_koszyk_id,$this->_));
    }
  }

  function delete($db) {
    if(is_null($this->_)) {
      return;
    }
    else {
      $query = $db->prepare("DELETE FROM `koszyk_film` WHERE ``=? LIMIT 1;");
      $query->execute(array($this->_));
    }
  }

  function get($db,$id) {
    if(gettype($id) != "integer") {
      throw new Exception("Value not integer");
    }
    else {
      $query = $db->prepare("SELECT ``,`film_id`,`koszyk_id` FROM `koszyk_film` WHERE ``=? LIMIT 1;");
      $query->execute(array($id));
      foreach ($query->fetchAll() as $row_id => $row_data) {
        $this->_ = $row_data[""];
        $this->_film_id = $row_data["film_id"];
        $this->_koszyk_id = $row_data["koszyk_id"];
      }
    }
  }
}