<?php
//////////////////////////////////////////////////////////////
// This class generated by a tool on 2015-02-13 at 13:51:58 //
//////////////////////////////////////////////////////////////
// importowanie obiektu dostawa
require 'dostawa.php';
class Zamowienie { 
  public $_id = null;
  public $_czas_zamowienia = null;
  public $_dostawa;

   public function __construct()
   {
    // Ustawienie dostawy jako nowy obiekt
    $this->_dostawa = new Dostawa();
   }
  function save($db) {
    if(is_null($this->_id)) {

      $this->_dostawa->save($db);
      echo $this->_dostawa->_id;
      $query = $db->prepare("INSERT INTO `zamowienie` (`dostawa_id`) VALUES (?);");
      $query->execute(array($this->_dostawa->_id));
      $this->_id = $db->lastInsertId();
      // Wstawienie dostawy 

      echo "Dodałem do bazy";
    }
    else {
      $query = $db->prepare("UPDATE `zamowienie` SET `czas_zamowienia`=?,`dostawa_id`=? WHERE `id`=? LIMIT 1;");
      $query->execute(array($this->_czas_zamowienia,$this->_dostawa->_id,$this->_id));
    }
  }

  function delete($db) {
    if(is_null($this->_id)) {
      return;
    }
    else {
      $query = $db->prepare("DELETE FROM `zamowienie` WHERE `id`=? LIMIT 1;");
      $query->execute(array($this->_id));
      $tihs->_dostawa->delete($db);
    }
  }

  function get($db,$id) {
    $query = $db->prepare("SELECT `id`,`czas_zamowienia`,`dostawa_id` FROM `zamowienie` WHERE `id`=? LIMIT 1;");
    $query->execute(array($id));
    foreach ($query->fetchAll() as $row_id => $row_data) {
      $this->_id = $row_data["id"];
      $this->_czas_zamowienia = $row_data["czas_zamowienia"];
      $this->_dostawa->get($db,  $row_data["dostawa_id"]);
    }
  }
}

//////////////////////////////////////////////////////////////
// This class generated by a tool on 2015-02-13 at 13:51:58 //
//////////////////////////////////////////////////////////////
class koszyk_film { 
  private $_film_id = null;
  private $_koszyk_id = null;

  function getfilm_id() {
    return (int)$this->_film_id;
  }
  function getkoszyk_id() {
    return (int)$this->_koszyk_id;
  }
  function setfilm_id($newvalue) {
    if(is_null($newvalue)) {
      throw new Exception("Value cannot be null - film_id");
    }
    if(gettype($newvalue) != "integer") {
      throw new Exception("Value not integer - ".$newvalue);
    }
    if(strlen($newvalue) > 11) {
      throw new Exception("Value size larger then then - 11 - ".$newvalue);
    }
    $this->_film_id = (int)$newvalue;
  }
  function setkoszyk_id($newvalue) {
    if(is_null($newvalue)) {
      throw new Exception("Value cannot be null - koszyk_id");
    }
    if(gettype($newvalue) != "integer") {
      throw new Exception("Value not integer - ".$newvalue);
    }
    if(strlen($newvalue) > 11) {
      throw new Exception("Value size larger then then - 11 - ".$newvalue);
    }
    $this->_koszyk_id = (int)$newvalue;
  }

  function save($db) {
    if(is_null($this->_)) {
      $query = $db->prepare("INSERT INTO `koszyk_film` VALUES (?,?);");
      $query->execute(array($this->_film_id,$this->_koszyk_id));
      $this->_ = $db->lastInsertId();
    }
    else {
      $query = $db->prepare("UPDATE `koszyk_film` SET `film_id`=?,`koszyk_id`=? WHERE ``=? LIMIT 1;");
      $query->execute(array($this->_film_id,$this->_koszyk_id,$this->_));
    }
  }

  function delete($db) {
    if(is_null($this->_)) {
      return;
    }
    else {
      $query = $db->prepare("DELETE FROM `koszyk_film` WHERE ``=? LIMIT 1;");
      $query->execute(array($this->_));
    }
  }

  function get($db,$id) {
    if(gettype($id) != "integer") {
      throw new Exception("Value not integer");
    }
    else {
      $query = $db->prepare("SELECT ``,`film_id`,`koszyk_id` FROM `koszyk_film` WHERE ``=? LIMIT 1;");
      $query->execute(array($id));
      foreach ($query->fetchAll() as $row_id => $row_data) {
        $this->_ = $row_data[""];
        $this->_film_id = $row_data["film_id"];
        $this->_koszyk_id = $row_data["koszyk_id"];
      }
    }
  }
}